name: "Manik Rathee"
description: "&emdash;Designer&#007C Photographer"
url: http://manikrathee.com/

#gems:        []
#timezone:    nil
#encoding:    nil

source: _prebuild/
# permalink: /blog/posts/:year/:month/:day/:title.html
permalink: /blog/:title.html
verbose: true
incremental: false
quiet:    false
safe: false
lsi: false
# highlighter: true
host: 127.0.0.1
port: 4000

# include: [".htaccess"]
exclude: ['gruntfile.js', 'package.json', '/node_modules', '*.psd']
keep_files:  ['.git','.htaccess','.well-known']
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# markdown: kramdown

sitemap:
    file: "/sitemap.xml"
    include_posts:
      - "/*.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

