name: 'Manik Rathee'
description: ' &emdash; Designer&#007C Photographer'
url: http://manikrathee.com/

#gems:        []
#timezone:    nil
#encoding:    nil

host: 127.0.0.1
port: 4000
source: _prebuild/
# permalink: /blog/posts/:year/:month/:day/:title.html
# permalink: /blog/:title.html
permalink: /blog/:slug.html
verbose: true
incremental: false
quiet:    false
safe: false
lsi: false
# markdown: kramdown
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
# highlighter: true
# include: ['.htaccess']
exclude: ['gruntfile.js', 'package.json', '/node_modules', '*.psd', '*.sketch']
keep_files:  ['.git','.htaccess','.well-known']
encoding:     'utf-8'


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      sitemap:
        lastmod: {{ post.date }}
        priority: 0.7
        changefreq: monthly
        exclude: 'no'


sitemap:
  file: '/sitemap.xml'
  include_posts:
    - '/*.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'
