name: 'Manik Rathee'
description: ' &emdash; Designer&#007C Photographer'
url: http://manikrathee.com/

#gems:        []
#timezone:    nil
encoding       : 'utf-8'

host           : manik.dev
# host           : 127.0.0.1
port           : 4000
source         : _prebuild/
# permalink    : /blog/posts/:year/:month/:day/:title.html
# permalink    : /blog/:title.html
permalink      : /:slug.html
verbose        : false
incremental    : false
quiet          : false
safe           : true
lsi            : false
markdown     : kramdown
markdown_ext : 'markdown,mkdown,mkdn,mkd,md'
highlighter  : true
# include      : ['.htaccess']
exclude        : ['gruntfile.js', 'package.json', '/node_modules', '*.psd', '*.sketch']
keep_files     : ['.git','.htaccess','.well-known']


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      sitemap:
        lastmod: {{ post.date }}
        priority: 0.7
        # changefreq: daily
        exclude: 'no'


sitemap:
  file: '/sitemap.xml'
  include_posts:
    - '/*.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'
